server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://45.78.69.161:8889/eureka/,http://45.78.69.161:8888/eureka/

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: feign-service
  zipkin:
    base-url: http://localhost:7500


