server:
  port: 7889
spring:
  application:
    name: consume
  cloud:
    stream:
      kafka:
        binder:
          brockers: localhost:9092
          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        myInput:
          destination: steam-demo
          content-type: text/plain
          group: group
