server:
  port: 7000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liyuItem/buy-config.git
          username: 504118543@qq.com
          password: liyuLOVE987

eureka:
  client:
    service-url:
      defaultZone: http://45.78.69.161:8889/eureka/,http://45.78.69.161:8888/eureka/

management:
  security:
    enabled: false
